<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <LangVersion>latest</LangVersion>

        <!-- Change this from 'embedded' to 'portable' or 'none' for releases -->
        <DebugType>portable</DebugType>
    
        <!-- Enable deterministic builds and map local paths to a generic root -->
        <Deterministic>true</Deterministic>
        <PathMap>$(MSBuildProjectDirectory)=/_/</PathMap>

        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <AssemblyName>MenaceMenuV1.1.2</AssemblyName>
        <VersionPrefix>4.2.1</VersionPrefix>
        <Description>Among Us cheat menu based on MalumMenu by scp222thj and Astral</Description>
        <Authors>ADHyperActive</Authors>
        <UnityBaseLibsDirectory>C:\Program Files\Unity\Hub\Editor\2022.3.62f3\Editor\Data\PlaybackEngines\windowsstandalonesupport\Variations\il2cpp\Managed</UnityBaseLibsDirectory>
    </PropertyGroup>

    <!--<ItemGroup>
        <EmbeddedResource Include=".\Assets\**" />
    </ItemGroup>-->

    <ItemGroup>
        <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.735" Private="false" ExcludeAssets="runtime;native" />
        <PackageReference Include="AmongUs.GameLibs.Steam" Version="2026.8.18" PrivateAssets="all" />

        <PackageReference Include="BepInEx.AutoPlugin" Version="1.1.0" PrivateAssets="all" />
        <PackageReference Include="BepInEx.IL2CPP.MSBuild" Version="2.1.0-rc.1" PrivateAssets="all" ExcludeAssets="runtime" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="routines\" />
    </ItemGroup>

    <Target Name="Copy" AfterTargets="Build" Condition="'$(AmongUs)' != ''">
        <!-- Copies the main compiled DLL -->
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(AmongUs)/BepInEx/plugins/" UseSymboliclinksIfPossible="true" />
        <!-- Copies the dependencies JSON configuration -->
        <Copy SourceFiles="$(TargetDir)$(TargetName).deps.json" DestinationFolder="$(AmongUs)/BepInEx/plugins/" UseSymboliclinksIfPossible="true" />
    </Target>
</Project>